CC = gcc
FLAGS = -g -O0

all : Duplicate_zeros merge_sorted_array remove_element remove_duplicates_from_sorted_array

%.o : %.c
	$(CC) $(FLAGS) -o $^

clean :
	rm -rf *.o Duplicate_zeros merge_sorted_array remove_element remove_duplicates_from_sorted_array
